# Generated by Django 4.2 on 2023-06-23 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('body', models.TextField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='HTML',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('video_link', models.URLField(unique=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(default='core/static/media/html_css.jpg', upload_to='core/static/media')),
                ('notes', models.FileField(blank=True, null=True, upload_to='core/static/notes')),
            ],
            options={
                'verbose_name_plural': 'HTML',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='JS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('video_link', models.URLField(unique=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(default='core/static/media/js.png', upload_to='core/static/media')),
                ('notes', models.FileField(blank=True, null=True, upload_to='core/static/notes')),
            ],
            options={
                'verbose_name_plural': 'JS',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='PYTHON',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('video_link', models.URLField(unique=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(default='core/static/media/images.png', upload_to='core/static/media')),
                ('notes', models.FileField(blank=True, null=True, upload_to='core/static/notes')),
            ],
            options={
                'verbose_name_plural': 'Python',
                'ordering': ('-created_at',),
            },
        ),
    ]
