# Generated by Django 4.2 on 2023-06-23 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('choices', models.CharField(blank=True, choices=[('html/css', 'HTML|CSS'), ('js', 'Js'), ('python', 'Python')], max_length=8, null=True)),
                ('assignments', models.FileField(blank=True, null=True, upload_to='core/static/students_assigments')),
                ('posted_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
