# Generated by Django 4.2 on 2023-06-23 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_assignments'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assignments',
            options={'ordering': ('-posted_at',), 'verbose_name_plural': 'Assignments'},
        ),
        migrations.RenameField(
            model_name='assignments',
            old_name='choices',
            new_name='courses',
        ),
    ]
